# frozen_string_literal: true

source 'https://rubygems.org'

ruby ENV['CUSTOM_RUBY_VERSION'] || '2.4.1'
gem 'activerecord'
gem 'bcrypt'
gem 'bundler'
gem 'haml' 
gem 'mail'
gem 'pg'
gem 'rack-cache'
gem 'rack-test'
gem 'rake' 
gem 'rspec'
gem 'rspec-mocks'
gem 'shotgun'
gem 'simplecov'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-flash'
gem 'spec'
