development:
  adapter: postgresql
  encoding: unicode
  database: learning_app_dev
  pool: 2
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: <%=ENV['DB_DATABASE_NAME']%>
  pool: 2
  username: <%=ENV['DB_USERNAME']%>
  password: <%=ENV['DB_PASSWORD']%>
  host: <%=ENV['DB_HOST']%>

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: test_learning_app
  pool: 2
  username: postgres
  password: 
